language: node_js

cache: yarn
notifications:
  email:
    on_success: never
    on_failure: change

script: npm test -- --ci

addons:
  apt:
    packages:
      - xvfb

before_install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
